from .common import ActionEntry as ActionEntry, ActionReturn as ActionReturn, ConcurrentBreakPoint as ConcurrentBreakPoint, Graph as Graph, Groups as Groups, ToolCall as ToolCall, UNSPECIFIED as UNSPECIFIED, UsageData as UsageData
from .context import Context as Context
from .utils import apply_placeholders as apply_placeholders, unwrap_exceptions as unwrap_exceptions, uuid as uuid
from _typeshed import Incomplete
from collections.abc import Generator
from pydantic import BaseModel
from typing import Any, Generic, TypeVar

DEFAULT_ACTION: Incomplete
DEFAULT_TOOL_CALL_PROMPT: Incomplete
TAction = TypeVar('TAction', bound='Action')
TContext = TypeVar('TContext', bound='Context')
T = TypeVar('T')
type ChildActions = dict[str, type['Action']]

class Action(BaseModel, Generic[TContext]):
    __enabled__: bool
    __system_prompt__: str | None
    __tool_call_prompt__: str | None
    __temperature__: float | None
    __max_tool_prompts__: int | None
    __default_tool__ = DEFAULT_ACTION
    __first_tool_only__: bool
    __concurrent__: bool
    __has_pre__: bool
    __has_fallback__: bool
    __has_on_error__: bool
    __has_post__: bool
    __has_as_tool__: bool
    __detached__: bool
    __max_iteration__: int | None
    __max_child_iteration__: int | None
    __child_actions__: ChildActions
    __agent__: bool
    __display_name__: str
    __groups__: Groups | set[str] | None
    __to_commit__: bool
    @classmethod
    def __pydantic_init_subclass__(cls, **kwargs: Any) -> None: ...
    @classmethod
    def __init_child_actions__(cls) -> None: ...
    async def pre(self, context: TContext) -> ActionReturn: ...
    async def fallback(self, context: TContext, content: str) -> ActionReturn: ...
    async def on_error(self, context: TContext, exception: Exception, unwrapped_exceptions: Generator[Exception, None, None]) -> ActionReturn: ...
    async def post(self, context: TContext) -> ActionReturn: ...
    async def commit_context(self, parent: TContext, child: TContext) -> None: ...
    def child_selection_prompt(self, context: TContext, tool_choice: str) -> str: ...
    async def get_child_actions(self, context: TContext) -> ChildActions: ...
    async def child_selection(self, context: TContext, child_actions: ChildActions | None = None) -> tuple[list['Action'], str]: ...
    async def execute(self, context: TContext, parent: Action | None = None, append: bool = True) -> ActionReturn: ...
    async def execute_concurrently(self, context: TContext, parent: Action | None = None, append: bool = True) -> None: ...
    async def execution(self, context: TContext) -> ActionReturn: ...
    async def concurrent_children_execution(self, context: TContext, next_actions: list[Action]) -> ActionReturn: ...
    async def sequential_children_execution(self, context: TContext, next_actions: list[Action]) -> ActionReturn: ...
    def serialize(self) -> ActionEntry: ...
    @classmethod
    def add_child(cls, action: type['Action'], name: str | None = None, override: bool = False, extended: bool = True) -> None: ...
    @classmethod
    def add_grand_child(cls, action: type['Action'], name: str | None = None, override: bool = False, extended: bool = True) -> None: ...
    @classmethod
    def remove_child(cls, name: str) -> None: ...
    @classmethod
    def remove_grand_child(cls, name: str) -> None: ...

def all_agents() -> Generator[type['Action']]: ...
async def graph(action: type[Action], allowed_actions: dict[str, bool] | None = None) -> Graph: ...
async def traverse(graph: Graph, action: type[Action], allowed_actions: dict[str, bool] | None) -> None: ...
