from .action import Action as Action, ActionReturn as ActionReturn, T as T, TAction as TAction
from .common import ChatRole as ChatRole, ToolCall as ToolCall, UNSPECIFIED as UNSPECIFIED, UsageMetadata as UsageMetadata
from .llm import LLM as LLM
from asyncio import Future
from collections.abc import Callable as Callable, Coroutine
from concurrent.futures import Executor
from functools import cached_property as cached_property
from langchain_core.language_models.chat_models import BaseChatModel
from pydantic import BaseModel
from typing import Any, Generic, ParamSpec, Self
from typing_extensions import TypeVar

TContext = TypeVar('TContext', bound='Context', default='Context')
TLLM = TypeVar('TLLM', default=BaseChatModel)
P = ParamSpec('P')

class Context(BaseModel, Generic[TLLM]):
    prompts: list[dict[str, Any]]
    allowed_actions: dict[str, bool]
    metadata: dict[str, Any]
    usages: dict[str, UsageMetadata]
    streaming: bool
    max_self_loop: int | None
    parent: Self | None
    @cached_property
    def llm(self) -> TLLM: ...
    async def start(self, action: type[TAction], /, **kwargs: Any) -> tuple[TAction, ActionReturn]: ...
    def check_self_recursion(self, action: Action) -> bool: ...
    async def merge_to_usages(self, model: str, usage: UsageMetadata) -> None: ...
    async def add_usage(self, action: Action, model: str | None, usage: UsageMetadata | None, name: str | None = None, raise_error: bool = False) -> None: ...
    async def add_message(self, role: ChatRole, content: str, metadata: dict[str, Any] | None = None) -> None: ...
    async def add_response(self, action: Action | ToolCall, content: str, metadata: dict[str, Any] | None = None) -> None: ...
    async def set_metadata(self, *paths: Any, value: Any, update: bool = False) -> None: ...
    async def update_metadata(self, *paths: Any, value: Any) -> None: ...
    async def notify(self, message: dict[str, Any]) -> None: ...
    def run_new_event_loop(self, task: Coroutine[Any, Any, T]) -> T: ...
    def run_task_in_thread(self, task: Coroutine[Any, Any, T], executor: Executor | None = None) -> Future[T]: ...
    def run_func_in_thread(self, task: Callable[P, T], executor: Executor | None = None, *args: P.args, **kwargs: P.kwargs) -> Future[T]: ...
    async def detach_context(self) -> TContext: ...
    def detached_kwargs(self, **kwargs: Any) -> dict[str, Any]: ...
    async def detached_start(self, action: type['Action'], /, **kwargs: Any) -> tuple[TContext, 'Action', ActionReturn]: ...
