from ..action import Action as Action, ChildActions as ChildActions
from ..common import ActionReturn as ActionReturn, ChatRole as ChatRole, Graph as Graph
from ..utils import is_camel_case as is_camel_case, unwrap_exceptions as unwrap_exceptions
from .common import MCPConfig as MCPConfig, MCPConnection as MCPConnection, MCPIntegration as MCPIntegration, MCPMode as MCPMode
from .context import TContext as TContext
from collections.abc import AsyncGenerator, AsyncIterator, Awaitable
from contextlib import AsyncExitStack, asynccontextmanager
from datamodel_code_generator.model import DataModelSet as DataModelSet
from mcp import ClientSession, Tool as Tool
from mcp.server.fastmcp import FastMCP
from mcp.shared.session import ProgressFnT as ProgressFnT
from mcp.types import ContentBlock as ContentBlock
from starlette.applications import AppType as AppType, Starlette
from typing import Any, Callable, Generic, Literal

DMT: DataModelSet

class MCPClient:
    session: ClientSession
    name: str
    config: MCPConfig
    manual_enable: bool
    allowed_tools: dict[str, bool]
    tool_action_class: type['MCPToolAction']
    exclude_unset: bool
    def __init__(self, session: ClientSession, name: str, config: MCPConfig, manual_enable: bool, allowed_tools: dict[str, bool], tool_action_class: type['MCPToolAction'] | None, exclude_unset: bool) -> None: ...
    def build_tool(self, tool: Tool) -> tuple[str, type['MCPToolAction']]: ...
    async def patch_tools(self, actions: ChildActions, mcp_actions: ChildActions) -> ChildActions: ...

class MCPAction(Action[TContext]):
    __mcp_servers__: dict[str, FastMCP]
    __mcp_clients__: dict[str, MCPClient]
    __mcp_connections__: list[MCPConnection]
    __mcp_tool_actions__: ChildActions
    __has_pre_mcp__: bool
    @classmethod
    def __pydantic_init_subclass__(cls, **kwargs: Any) -> None: ...
    @classmethod
    def __init_child_actions__(cls) -> None: ...
    async def pre_mcp(self, context: TContext) -> ActionReturn: ...
    _parent: Action | None
    __to_commit__: bool
    async def execute(self, context: TContext, parent: Action | None = None, append: bool = True) -> ActionReturn: ...
    async def get_child_actions(self, context: TContext) -> ChildActions: ...
    @classmethod
    def add_child(cls, action: type['Action'], name: str | None = None, override: bool = False, extended: bool = True) -> None: ...

class MCPToolAction(Action[TContext], Generic[TContext]):
    __mcp_tool__: bool
    __mcp_client__: MCPClient
    __mcp_tool_name__: str
    __mcp_exclude_unset__: bool
    def build_progress_callback(self, context: TContext) -> ProgressFnT: ...
    def clean_content(self, content: ContentBlock) -> str: ...
    async def pre(self, context: TContext) -> ActionReturn: ...

@asynccontextmanager
async def multi_mcp_clients(integrations: dict[str, MCPIntegration], connections: list[MCPConnection], bypass: bool = False) -> AsyncIterator[dict[str, MCPClient]]: ...
def initialize_mcp_groups() -> None: ...
@asynccontextmanager
async def mount_mcp_app(app: AppType, *groups: str, transport: Literal['sse', 'streamable-http'] | dict[str, str] = 'streamable-http') -> AsyncGenerator[AsyncExitStack, None]: ...
def build_mcp_app(*groups: str, transport: Literal['sse', 'streamable-http'] | dict[str, str] = 'streamable-http') -> Starlette: ...
def build_mcp_entry(action: type['Action']) -> Callable[..., Awaitable[str]]: ...
def add_mcp_tool(group: str, action: type['Action'], entry: Callable[..., Awaitable[str]]) -> None: ...
async def graph(action: type[Action], allowed_actions: dict[str, bool] | None = None, integrations: dict[str, MCPIntegration] | None = None, bypass: bool = False) -> Graph: ...
async def traverse(graph: Graph, action: type[Action], allowed_actions: dict[str, bool] | None, integrations: dict[str, MCPIntegration], bypass: bool = False) -> None: ...
