from ..action import Action as Action, ChildActions as ChildActions
from ..common import ActionReturn as ActionReturn, Graph as Graph
from ..utils import unwrap_exceptions as unwrap_exceptions
from .common import GRPCConfigLoaded as GRPCConfigLoaded, GRPCConnection as GRPCConnection, GRPCIntegration as GRPCIntegration
from .context import TContext as TContext
from .exception import GRPCRemoteError as GRPCRemoteError
from .pybotchi_pb2 import ActionListRequest as ActionListRequest, ActionListResponse as ActionListResponse, ActionSchema as ActionSchema, Event as Event, TraverseGraph as TraverseGraph, TraverseRequest as TraverseRequest
from .pybotchi_pb2_grpc import PyBotchiGRPCStub as PyBotchiGRPCStub
from _typeshed import Incomplete
from asyncio import Queue
from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager
from typing import Any, Generic

DMT: Incomplete

class GRPCClient:
    stub: Incomplete
    name: Incomplete
    config: Incomplete
    manual_enable: Incomplete
    allowed_actions: Incomplete
    remote_action_class: Incomplete
    exclude_unset: Incomplete
    def __init__(self, stub: PyBotchiGRPCStub, name: str, config: GRPCConfigLoaded, manual_enable: bool, allowed_actions: dict[str, bool], remote_action_class: type['GRPCRemoteAction'] | None, exclude_unset: bool) -> None: ...
    def build_action(self, agent_id: str, action_schema: ActionSchema) -> tuple[str, type['GRPCRemoteAction']]: ...
    async def patch_actions(self, actions: ChildActions, grpc_actions: ChildActions) -> ChildActions: ...

class GRPCAction(Action[TContext], Generic[TContext]):
    __grpc_clients__: dict[str, GRPCClient]
    __grpc_connections__: list[GRPCConnection]
    __grpc_tool_actions__: ChildActions
    __has_pre_grpc__: bool
    @classmethod
    def __pydantic_init_subclass__(cls, **kwargs: Any) -> None: ...
    @classmethod
    def __init_child_actions__(cls) -> None: ...
    async def pre_grpc(self, context: TContext) -> ActionReturn: ...
    __to_commit__: bool
    async def execute(self, context: TContext, parent: Action | None = None, append: bool = True) -> ActionReturn: ...
    async def get_child_actions(self, context: TContext) -> ChildActions: ...
    @classmethod
    def add_child(cls, action: type['Action'], name: str | None = None, override: bool = False, extended: bool = True) -> None: ...

class GRPCRemoteAction(Action[TContext], Generic[TContext]):
    __grpc_action__: bool
    __grpc_client__: GRPCClient
    __grpc_group__: str
    __grpc_action_name__: str
    __grpc_exclude_unset__: bool
    __grpc_queue__: Queue[Event]
    async def grpc_event_close(self, context: TContext, event: Event) -> None: ...
    async def grpc_event_error(self, context: TContext, event: Event) -> None: ...
    async def grpc_event_update(self, context: TContext, event: Event) -> None: ...
    async def grpc_queue(self, context: TContext) -> AsyncGenerator[Event, None]: ...
    async def grpc_send(self, name: str, data: dict[str, Any] | None = None) -> None: ...
    async def grpc_consume(self, context: TContext, event: Event) -> None: ...
    async def grpc_connect(self, context: TContext, payload: dict[str, Any], metadata: dict[str, Any] | None = None) -> AsyncGenerator[Event, None]: ...
    async def pre(self, context: TContext) -> ActionReturn: ...

@asynccontextmanager
async def multi_grpc_clients(integrations: dict[str, GRPCIntegration], connections: list[GRPCConnection], bypass: bool = False) -> AsyncGenerator[dict[str, GRPCClient], None]: ...
async def graph(action: type[Action], allowed_actions: dict[str, bool] | None = None, integrations: dict[str, GRPCIntegration] | None = None, bypass: bool = False) -> Graph: ...
async def traverse(graph: Graph, action: type[Action], allowed_actions: dict[str, bool] | None, integrations: dict[str, GRPCIntegration], bypass: bool = False, module: str | None = None, alias: str | None = None) -> None: ...
