from multiprocessing import Process
from pybotchi import Action as Action
from pybotchi.utils import uuid as uuid
from types import FrameType

PROCESSES: list[Process]

async def serve(id: str, path: str, host: str, port: str, root_certificates: bytes | None, private_key: bytes | None, certificate_chain: bytes | None, require_client_auth: bool) -> None: ...
def terminate(sig: int, frame: FrameType | None) -> None: ...
def start(id: str, path: str, host: str, port: str, root_certificates: bytes | None, private_key: bytes | None, certificate_chain: bytes | None, require_client_auth: bool) -> None: ...
def main(path: str, id: str | None, host: str | None, port: str | None, workers: str | None, root_certificates: str | None, private_key: str | None, certificate_chain: str | None, require_client_auth: bool) -> None: ...
def compile() -> None: ...
