from ..common import ToolCall as ToolCall
from ..context import Action as Action, ChatRole as ChatRole, Context as Context, TLLM as TLLM
from ..utils import uuid as uuid
from .common import GRPCIntegration as GRPCIntegration
from .pybotchi_pb2 import Event as Event
from typing import Any, Generic, TypeVar

TContext = TypeVar('TContext', bound='GRPCContext')

class GRPCContext(Context[TLLM], Generic[TLLM]):
    integrations: dict[str, GRPCIntegration]
    source_id: str | None
    context_id: str
    def grpc_dump(self) -> dict[str, Any]: ...
    def grpc_sharing_dump(self) -> dict[str, Any]: ...
    async def grpc_send_up(self, source_id: str | None, name: str, data: dict[str, Any]) -> None: ...
    async def grpc_send_down(self, source_id: str | None, name: str, data: dict[str, Any]) -> None: ...
    def detached_kwargs(self, **kwargs: Any) -> dict[str, Any]: ...
    async def add_message(self, role: ChatRole, content: str, metadata: dict[str, Any] | None = None, source_id: str | None = None) -> None: ...
    async def add_response(self, action: Action | ToolCall, content: str, metadata: dict[str, Any] | None = None, source_id: str | None = None) -> None: ...
    async def set_metadata(self, *paths: Any, value: Any, update: bool = False, source_id: str | None = None) -> None: ...
    async def notify(self, message: dict[str, Any]) -> None: ...
