from ..action import Action as Action
from ..common import Graph as Graph
from ..utils import uuid as uuid
from .action import traverse as traverse
from .context import GRPCContext as GRPCContext, TContext as TContext
from .exception import GRPCRemoteError as GRPCRemoteError
from .pybotchi_pb2 import ActionListRequest as ActionListRequest, ActionListResponse as ActionListResponse, ActionSchema as ActionSchema, Edge as Edge, Event as Event, JSONSchema as JSONSchema, TraverseGraph as TraverseGraph, TraverseRequest as TraverseRequest
from .pybotchi_pb2_grpc import PyBotchiGRPCServicer as PyBotchiGRPCServicer
from _typeshed import Incomplete
from asyncio import Queue
from collections.abc import AsyncGenerator
from grpc.aio import Metadata as Metadata, ServicerContext as ServicerContext
from typing import Generic

class PyBotchiGRPC(PyBotchiGRPCServicer, Generic[TContext]):
    __context_class__: type[TContext]
    __allow_exec__: bool
    id: Incomplete
    module: Incomplete
    groups: Incomplete
    __has_validate_metadata__: Incomplete
    def __init__(self, id: str, module: str, groups: dict[str, dict[str, type[Action]]]) -> None: ...
    async def validate_metadata(self, metadata: Metadata | None) -> None: ...
    async def consume(self, context: TContext, groups: list[str], events: AsyncGenerator[Event, None]) -> None: ...
    async def grpc_event_execute(self, context: TContext, groups: list[str], event: Event) -> None: ...
    async def grpc_event_update(self, context: TContext, groups: list[str], event: Event) -> None: ...
    async def accept(self, events: AsyncGenerator[Event, None], context: ServicerContext) -> Queue[Event]: ...
    async def execute_connect(self, request_iterator: AsyncGenerator[Event, None], context: ServicerContext) -> AsyncGenerator[Event, None]: ...
    async def connect(self, request_iterator: AsyncGenerator[Event, None], context: ServicerContext) -> AsyncGenerator[Event, None]: ...
    async def action_list(self, request: ActionListRequest, context: ServicerContext) -> ActionListResponse: ...
    async def traverse(self, request: TraverseRequest, context: ServicerContext) -> TraverseGraph: ...
