"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import pybotchi_pb2 as _pybotchi_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class PyBotchiGRPCStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> PyBotchiGRPCAsyncStub: ...
    connect: _grpc.StreamStreamMultiCallable[_pybotchi_pb2.Event, _pybotchi_pb2.Event]
    action_list: _grpc.UnaryUnaryMultiCallable[_pybotchi_pb2.ActionListRequest, _pybotchi_pb2.ActionListResponse]
    traverse: _grpc.UnaryUnaryMultiCallable[_pybotchi_pb2.TraverseRequest, _pybotchi_pb2.TraverseGraph]

@_typing.type_check_only
class PyBotchiGRPCAsyncStub(PyBotchiGRPCStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    connect: _aio.StreamStreamMultiCallable[_pybotchi_pb2.Event, _pybotchi_pb2.Event]  # type: ignore[assignment]
    action_list: _aio.UnaryUnaryMultiCallable[_pybotchi_pb2.ActionListRequest, _pybotchi_pb2.ActionListResponse]  # type: ignore[assignment]
    traverse: _aio.UnaryUnaryMultiCallable[_pybotchi_pb2.TraverseRequest, _pybotchi_pb2.TraverseGraph]  # type: ignore[assignment]

class PyBotchiGRPCServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def connect(
        self,
        request_iterator: _MaybeAsyncIterator[_pybotchi_pb2.Event],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_pybotchi_pb2.Event], _abc.AsyncIterator[_pybotchi_pb2.Event]]: ...

    @_abc_1.abstractmethod
    def action_list(
        self,
        request: _pybotchi_pb2.ActionListRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_pybotchi_pb2.ActionListResponse, _abc.Awaitable[_pybotchi_pb2.ActionListResponse]]: ...

    @_abc_1.abstractmethod
    def traverse(
        self,
        request: _pybotchi_pb2.TraverseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_pybotchi_pb2.TraverseGraph, _abc.Awaitable[_pybotchi_pb2.TraverseGraph]]: ...

def add_PyBotchiGRPCServicer_to_server(servicer: PyBotchiGRPCServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
