from _typeshed import Incomplete

GRPC_GENERATED_VERSION: str
GRPC_VERSION: Incomplete

class PyBotchiGRPCStub:
    connect: Incomplete
    action_list: Incomplete
    traverse: Incomplete
    def __init__(self, channel) -> None: ...

class PyBotchiGRPCServicer:
    def connect(self, request_iterator, context) -> None: ...
    def action_list(self, request, context) -> None: ...
    def traverse(self, request, context) -> None: ...

def add_PyBotchiGRPCServicer_to_server(servicer, server) -> None: ...

class PyBotchiGRPC:
    @staticmethod
    def connect(request_iterator, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def action_list(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def traverse(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
